default: &default
  adapter: mysql2
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  host: db
  port: 3306
  username: root
  password: password

development:
  <<: *default
  database: advanced_development

test:
  <<: *default
  database: advanced_test

production:
  <<: *default
  database: production